// Builds slides/GroupP1-9.pptx. Load/stress/accuracy numbers are read from
// step5/results (generated by analyse_jtl.py and accuracy_test.py), so the deck
// reconciles with the logs.
// Run from the repo root:  node slides/build_deck.js   (needs pptxgenjs on NODE_PATH)
const fs = require("fs");
const path = require("path");
const pptxgen = require("pptxgenjs");

const ROOT = path.resolve(__dirname, "..");
const R = (p) => path.join(ROOT, p);
const OUT = R("slides/GroupP1-9.pptx");
const APPLY_THEME = process.env.APPLY_THEME; // path to the pptx skill's apply_theme.js (optional)

// ---------- data ----------
function readCsv(p) {
  const [head, ...lines] = fs.readFileSync(R(p), "utf8").trim().split(/\r?\n/);
  const cols = head.split(",");
  return lines.map((l) => Object.fromEntries(l.split(",").map((v, i) => [cols[i], v])));
}
const levels = readCsv("step5/results/levels.csv");
const lvl = (model, level, ep) => levels.find((r) => r.model === model && r.level === level && r.endpoint === ep);
const acc = Object.fromEntries(
  ["gemma3-1b", "qwen3-4b", "llama3.1-8b"].map((m) => [m, JSON.parse(fs.readFileSync(R(`step5/results/${m}/accuracy/summary.json`), "utf8"))])
);
const timeline = readCsv("step5/results/qwen3-4b/stress_60-1200ph_40min/run1/timeline.csv");
const hist = readCsv("workload/ticket_lengths_hist.csv").filter((r) => +r.tickets > 0);

const MODELS = [
  { key: "gemma3-1b", name: "Gemma 3 1B", color: "8E9AA3" },
  { key: "qwen3-4b", name: "Qwen3 4B", color: "2A9D8F" },
  { key: "llama3.1-8b", name: "Llama 3.1 8B", color: "E07A1F" },
];
const CATS = ["Credit reporting", "Debt collection", "Mortgage", "Credit card", "Bank account or service", "Consumer loan", "Money transfer or service"];
const s = (ms, d = 1) => (+ms / 1000).toFixed(d);

// ---------- theme ----------
const THEME = {
  name: "Triage Teal",
  headFontFace: "Cambria",
  bodyFontFace: "Calibri",
  colors: {
    dk1: "1B2A30", lt1: "FFFFFF", dk2: "12343B", lt2: "EEF3F4",
    accent1: "2A9D8F", accent2: "E07A1F", accent3: "8E9AA3", accent4: "C0392B",
    accent5: "3D6B73", accent6: "F2C14E", hlink: "1F6F8B", folHlink: "5B4B8A",
  },
};
const HEX = THEME.colors;
const PASS = "2A9D8F", FAIL = "C0392B", WARN = "E07A1F";

const pres = new pptxgen();
pres.layout = "LAYOUT_16x9"; // 10 x 5.625 in
pres.theme = { headFontFace: THEME.headFontFace, bodyFontFace: THEME.bodyFontFace };
pres.title = "Group P1-9 ICT3113 Assignment 1";
pres.author = "Group P1-9";
const C = pres.SchemeColor;

pres.defineSlideMaster({
  title: "DARK",
  background: { color: HEX.dk2 },
  objects: [],
});
pres.defineSlideMaster({
  title: "CONTENT",
  background: { color: HEX.lt1 },
  margin: [0.4, 0.5, 0.4, 0.5],
  objects: [
    { placeholder: { options: { name: "title", type: "title", x: 0.5, y: 0.25, w: 9.0, h: 0.6, fontSize: 22, bold: true, color: C.text2, fontFace: THEME.headFontFace, valign: "middle", align: "left", margin: 0 }, text: "" } },
    { text: { text: "Group P1-9 · ICT3113 Assignment 1", options: { x: 0.5, y: 5.3, w: 5, h: 0.25, fontSize: 9, color: C.accent3, margin: 0 } } },
  ],
  slideNumber: { x: 9.0, y: 5.3, w: 0.5, h: 0.25, fontSize: 9, color: HEX.accent3, align: "right" },
});

// ---------- helpers ----------
const txt = (slide, text, o) => slide.addText(text, { isTextBox: true, margin: 0, fontSize: 12, color: C.text1, valign: "top", ...o });
function card(slide, x, y, w, h, fill = HEX.lt2) {
  slide.addShape(pres.shapes.ROUNDED_RECTANGLE, { x, y, w, h, fill: { color: fill }, line: { color: fill }, rectRadius: 0.08 });
}
function stat(slide, x, y, w, big, label, color = C.text2) {
  txt(slide, big, { x, y, w, h: 0.5, fontSize: 26, bold: true, color, fontFace: THEME.headFontFace });
  txt(slide, label, { x, y: y + 0.5, w, h: 0.45, fontSize: 10, color: C.text1 });
}
const hdr = (t) => ({ text: t, options: { bold: true, color: "FFFFFF", fill: { color: HEX.dk2 } } });
const cell = (t, o = {}) => ({ text: String(t), options: o });
function verdict(v) {
  const color = v.startsWith("PASS") ? PASS : v.startsWith("FAIL") ? FAIL : WARN;
  return cell(v, { bold: true, color: "FFFFFF", fill: { color }, align: "center" });
}
function contentSlide(title, section) {
  const sl = pres.addSlide({ masterName: "CONTENT", sectionTitle: section });
  sl.addText(title, { placeholder: "title", fontSize: 22, align: "left" });
  return sl;
}

// ================= 1 Cover =================
pres.addSection({ title: "Context" });
{
  const sl = pres.addSlide({ masterName: "DARK", sectionTitle: "Context" });
  txt(sl, "ICT3113 Assignment 1 · Performance Requirements & Testing", { x: 0.6, y: 0.55, w: 8.8, h: 0.3, fontSize: 12, color: "CFE3E0" });
  txt(sl, "Complaint Triage on CPU-Only Hardware", { x: 0.6, y: 0.95, w: 8.8, h: 0.7, fontSize: 30, bold: true, color: "FFFFFF", fontFace: THEME.headFontFace });
  txt(sl, "Which local model to deploy, and what service quality can be promised", { x: 0.6, y: 1.72, w: 8.8, h: 0.4, fontSize: 16, italic: true, color: "CFE3E0" });
  txt(sl, "Group P1-9", { x: 0.6, y: 2.5, w: 4, h: 0.4, fontSize: 20, bold: true, color: HEX.accent6, fontFace: THEME.headFontFace });
  const members = Array.from({ length: 5 }, (_, i) => `[Member ${i + 1} name] · [Student ID]`);
  txt(sl, members.map((m, i) => ({ text: m, options: { breakLine: i < 4 } })), { x: 0.6, y: 2.95, w: 5.2, h: 1.6, fontSize: 13, color: "FFFFFF", paraSpaceAfter: 4 });
  txt(sl, [
    { text: "Repository: ", options: { color: "CFE3E0" } },
    { text: "github.com/anarchygene/ICT3113_Assignment_1", options: { color: "FFFFFF", hyperlink: { url: "https://github.com/anarchygene/ICT3113_Assignment_1" } } },
  ], { x: 0.6, y: 4.75, w: 8.8, h: 0.3, fontSize: 12 });
  card(sl, 6.3, 2.5, 3.1, 1.95, "1D4A52");
  txt(sl, [
    { text: "Rebuild & run", options: { bold: true, color: HEX.accent6, breakLine: true } },
    { text: "cp .env.example .env", options: { breakLine: true } },
    { text: "docker compose up -d --build", options: { breakLine: true } },
    { text: "Step 5 playbook: step5/README.md", options: { breakLine: true } },
    { text: "Results: step5/RESULTS.md" },
  ], { x: 6.5, y: 2.65, w: 2.8, h: 1.7, fontSize: 11, color: "FFFFFF", fontFace: "Courier New", paraSpaceAfter: 3 });
  sl.addNotes("Group P1-9. Members and student IDs to be filled in. The repository contains the service, docker compose file, golden set, frozen prediction record (STEP4.md, freeze commit 3567f80), all JMeter .jtl files and service logs.");
}

// ================= 2 Architecture =================
{
  const sl = contentSlide("Architecture: one synchronous model call per ticket", "Context");
  // load generator
  card(sl, 0.5, 1.15, 1.75, 1.3, "FBEBDD");
  txt(sl, [{ text: "Load-generator PC", options: { bold: true, breakLine: true } }, { text: "Apache JMeter 5.6.3, open-loop Open Model Thread Groups" }], { x: 0.62, y: 1.25, w: 1.55, h: 1.1, fontSize: 11 });
  // service PC boundary
  sl.addShape(pres.shapes.ROUNDED_RECTANGLE, { x: 2.75, y: 0.95, w: 3.45, h: 3.95, fill: { color: "F6F9F9" }, line: { color: HEX.accent3, dashType: "dash", width: 1 }, rectRadius: 0.08 });
  txt(sl, "Service PC · Docker Compose", { x: 2.9, y: 1.02, w: 3.2, h: 0.25, fontSize: 10, bold: true, color: C.accent5 });
  const box = (y, title, sub, fill) => {
    card(sl, 3.0, y, 2.95, 0.95, fill);
    txt(sl, [{ text: title, options: { bold: true, breakLine: true } }, { text: sub }], { x: 3.12, y: y + 0.08, w: 2.75, h: 0.82, fontSize: 11 });
  };
  box(1.35, "Triage service (FastAPI)", "Validates, calls Ollama, stores, logs every request (id, path, status, duration)", "DDF0EE");
  box(2.55, "Ollama 0.12.3 · CPU only", "One model loaded; NUM_PARALLEL = 1, so tickets are classified one at a time", "FBEBDD");
  box(3.75, "PostgreSQL 16", "Starts empty; filled only through POST /tickets", "E4E9EC");
  const arrow = (x1, y1, x2, y2) => sl.addShape(pres.shapes.LINE, { x: x1, y: y1, w: x2 - x1, h: y2 - y1, line: { color: HEX.dk2, width: 1.5, endArrowType: "triangle" } });
  arrow(2.25, 1.8, 3.0, 1.8);
  arrow(4.475, 2.3, 4.475, 2.55);
  sl.addShape(pres.shapes.LINE, { x: 5.95, y: 1.82, w: 0.15, h: 0, line: { color: HEX.dk2, width: 1.5 } });
  sl.addShape(pres.shapes.LINE, { x: 6.1, y: 1.82, w: 0, h: 2.4, line: { color: HEX.dk2, width: 1.5 } });
  sl.addShape(pres.shapes.LINE, { x: 5.95, y: 4.22, w: 0.15, h: 0, line: { color: HEX.dk2, width: 1.5, beginArrowType: "triangle" } });
  txt(sl, "HTTP :8000, home LAN", { x: 0.5, y: 2.55, w: 2.2, h: 0.3, fontSize: 10, color: C.accent5 });
  // endpoints
  txt(sl, "Endpoints", { x: 6.55, y: 1.0, w: 3, h: 0.3, fontSize: 14, bold: true, color: C.text2 });
  txt(sl, [
    { text: "POST /tickets", options: { bold: true, breakLine: true } },
    { text: "Classifies one narrative into one of 7 categories, stores it, returns the category (201). Invalid model output → 502, not stored.", options: { breakLine: true } },
    { text: "GET /search?q=", options: { bold: true, breakLine: true } },
    { text: "Case-insensitive substring search of stored narratives.", options: { breakLine: true } },
    { text: "GET /stats", options: { bold: true, breakLine: true } },
    { text: "Count of stored tickets per category." },
  ], { x: 6.55, y: 1.35, w: 2.95, h: 2.3, fontSize: 11, paraSpaceAfter: 3 });
  card(sl, 6.55, 3.75, 2.95, 1.15, "DDF0EE");
  txt(sl, [
    { text: "Baseline, unoptimised", options: { bold: true, color: C.accent5, breakLine: true } },
    { text: "POST /tickets blocks until Ollama answers. No cache, no queue, no retries, no batching." },
  ], { x: 6.67, y: 3.85, w: 2.75, h: 1.0, fontSize: 11 });
  sl.addNotes("Prompt: fixed system prompt listing the seven exact category names, JSON output mode, temperature 0, num_ctx 4096 (app/classifier.py). JMeter runs on a separate PC; logs are kept in evidence/step5/logs.");
}

// ================= 3 Workload =================
pres.addSection({ title: "Requirements" });
{
  const sl = contentSlide("Workload: 81 tickets/h at peak, 105/h with growth headroom", "Requirements");
  stat(sl, 0.5, 1.0, 2.1, "189,070", "complaints/year: Barclays Bank UK, H1 2026 × 2 [S: R1]");
  stat(sl, 2.7, 1.0, 2.1, "81 / h", "present-day peak hour [E]", C.accent2);
  stat(sl, 0.5, 1.95, 2.1, "105 / h", "requirement load: peak + 30% growth [S: R5]", C.accent1);
  stat(sl, 2.7, 1.95, 2.1, "316 / h", "agent searches at 105/h (6 per agent-hour) [E]");
  txt(sl, [
    { text: "Derivation: ", options: { bold: true } },
    { text: "189,070 ÷ 365 = 518/day × 1.25 busiest day [S: CFPB daily counts, R3] = 648/day ÷ 12-h arrival window [E] × 1.5 busiest hour [E, bounded by R6/R7] = 81/h." },
  ], { x: 0.5, y: 2.9, w: 4.4, h: 0.7, fontSize: 10 });
  const rows = [
    [hdr("Level"), hdr("POST/h"), hdr("Search/h"), hdr("Tested")],
    ["Off-peak (Sunday)", "18", "55", "–"], ["Average", "43", "130", "3 runs"], ["Peak", "81", "243", "3 runs"],
    ["Peak + 30% (R1–R4)", "105", "316", "3 runs"], ["Burst / surge", "130 / 243", "316", "stress ramp"],
  ].map((r, i) => (i === 0 ? r : r.map((c) => cell(c))));
  sl.addTable(rows, { x: 0.5, y: 3.62, w: 4.4, colW: [1.7, 0.85, 0.85, 1.0], fontSize: 9.5, border: { type: "solid", color: "D5DEE1", pt: 0.5 }, rowH: 0.22, margin: 0.04 });
  sl.addChart(pres.charts.BAR, [{ name: "Tickets", labels: hist.map((h) => `${h.words_from}`), values: hist.map((h) => +h.tickets) }], {
    x: 5.2, y: 0.95, w: 4.3, h: 3.2, barDir: "col", chartColors: [HEX.accent5], showTitle: true, title: "Ticket length, words (rows 9000–9999) [M]",
    titleFontSize: 11, titleColor: HEX.dk2, titleFontFace: "+mn-lt", catAxisLabelFontSize: 8, valAxisLabelFontSize: 8, catAxisLabelColor: "5A6A70", valAxisLabelColor: "5A6A70",
    catAxisLabelFontFace: "+mn-lt", valAxisLabelFontFace: "+mn-lt", valGridLine: { color: "E1E7EA", size: 0.5 }, catGridLine: { style: "none" }, showLegend: false, barGapWidthPct: 30,
  });
  txt(sl, "Median 140 · p95 305 · p99 352 · max 369 words. Right-skewed; the extract is clipped at 200–2,000 characters, so real tickets can be longer and slower.", { x: 5.2, y: 4.2, w: 4.3, h: 0.6, fontSize: 10 });
  txt(sl, "[S] sourced · [E] estimate · [M] measured. Sources on slide 12; full derivation in workload/WORKLOAD.md.", { x: 5.2, y: 4.85, w: 4.3, h: 0.3, fontSize: 9, italic: true, color: C.accent5 });
  sl.addNotes("Sources: R1 Barclays UK complaints Jan–Jun 2026 (94,535 opened); R3 CFPB daily counts (busiest day 1.25× weekly mean); R5 FIDReC +32% claims against banks; R6 Call Centre Helper (40% of an hour's calls in the first 15 min → 1.6× burst, 130/h); R7 Taylor 2012 (busiest half-hour ~2× median, upper bound for the 1.5× hour factor). Estimates: 12-hour arrival window, 1.5× busiest hour, 30 min agent time per complaint, 6 searches per agent-hour, 3× incident surge (243/h).");
}

// ================= 4 Requirements =================
{
  const sl = contentSlide("Requirements: testable, identical for every candidate", "Requirements");
  txt(sl, "R1–R4 condition: open-loop mixed load, 105 POST/h + 316 search/h, 20-min steady window after a 2-min warm-up, 3 runs. R5–R7: the frozen 160-ticket golden set.", { x: 0.5, y: 0.9, w: 9, h: 0.4, fontSize: 11, color: C.accent5 });
  const rows = [
    [hdr("Req"), hdr("Testable statement"), hdr("Why this number")],
    ["R1 Throughput", "≥ 105 successful classifications/h; backlog not growing", "Peak 81/h + 30% one-year growth (FIDReC +32%)"],
    ["R2 POST latency", "p95 ≤ 30 s, p99 ≤ 60 s", "p95 below the 34 s mean gap between arrivals at 105/h, so queues drain; intake is automated, not interactive"],
    ["R3 Search latency", "p95 ≤ 2 s, p99 ≤ 5 s", "Agents search interactively while handling a case"],
    ["R4 Reliability", "≤ 1.0% errors per endpoint; /stats delta = successful POSTs", "A failed classification is an unrouted ticket"],
    ["R5 Accuracy", "≥ 85.0% overall (≥ 136/160)", "≥ 5 of 6 routed correctly, else manual correction cost dominates"],
    ["R6 Per category", "every category ≥ 70.0%", "Stops a small team (Credit card, n = 11) being sacrificed for the average"],
    ["R7 Conformance", "≥ 99.0% valid JSON with an exact category name", "Non-exact output cannot be routed"],
    ["R8 Deployment", "CPU-only local Ollama; 0 restarts or OOM kills", "Client compliance: no data leaves; no GPUs"],
  ].map((r, i) => (i === 0 ? r : [cell(r[0], { bold: true, color: HEX.dk2 }), cell(r[1]), cell(r[2], { color: "4A5A60" })]));
  sl.addTable(rows, { x: 0.5, y: 1.35, w: 9, colW: [1.45, 3.45, 4.1], fontSize: 10.5, border: { type: "solid", color: "D5DEE1", pt: 0.5 }, margin: 0.05, rowH: 0.36, valign: "middle" });
  sl.addNotes("Full statements and justifications in STEP4.md section 4 (frozen at commit 3567f80). Thresholds are the same for all three candidates and were not changed after results.");
}

// ================= 5 Candidate models =================
{
  const sl = contentSlide("Candidate models: three size classes, one quantisation", "Requirements");
  const cands = [
    { n: "Gemma 3 1B", cls: "Small · 1.0B", tag: "gemma3:1b-it-q4_K_M", id: "8648f39daa8f", sha: "7cd4618c1faf…", size: "815 MB", lic: "Gemma Terms of Use", why: "Fast, low-resource floor of the trade-off" },
    { n: "Qwen3 4B Instruct", cls: "Medium · 4.0B", tag: "qwen3:4b-instruct-2507-q4_K_M", id: "0edcdef34593", sha: "85e4a5b7b8ef…", size: "2.5 GB", lic: "Apache 2.0", why: "Predicted balance; non-thinking variant, no reasoning tokens" },
    { n: "Llama 3.1 8B Instruct", cls: "Large · 8.0B", tag: "llama3.1:8b-instruct-q4_K_M", id: "46e0c10c039e", sha: "667b0c1932bc…", size: "4.9 GB", lic: "Llama 3.1 Community License", why: "Accuracy ceiling a CPU server can plausibly run" },
  ];
  cands.forEach((c, i) => {
    const x = 0.5 + i * 3.05;
    card(sl, x, 1.0, 2.85, 2.6);
    sl.addShape(pres.shapes.OVAL, { x: x + 0.18, y: 1.15, w: 0.32, h: 0.32, fill: { color: MODELS[i].color }, line: { color: MODELS[i].color } });
    txt(sl, c.n, { x: x + 0.6, y: 1.12, w: 2.15, h: 0.38, fontSize: 15, bold: true, color: C.text2, fontFace: THEME.headFontFace, valign: "middle" });
    txt(sl, [
      { text: c.cls, options: { bold: true, color: MODELS[i].color, breakLine: true } },
      { text: c.tag, options: { fontFace: "Courier New", fontSize: 9.5, breakLine: true } },
      { text: `ID ${c.id} · weights sha256:${c.sha}`, options: { fontSize: 9.5, breakLine: true } },
      { text: `${c.size} · ${c.lic}`, options: { breakLine: true } },
      { text: c.why, options: { italic: true } },
    ], { x: x + 0.18, y: 1.6, w: 2.5, h: 1.95, fontSize: 11, paraSpaceAfter: 6 });
  });
  txt(sl, [
    { text: "Why this set: ", options: { bold: true } },
    { text: "parameters roughly double at each step, so the speed-versus-accuracy trade-off is visible across what a CPU server can run. Phi-4 Mini 3.8B was dropped before benchmarking because it duplicated the 4B class. " },
    { text: "Held constant: ", options: { bold: true } },
    { text: "Q4_K_M weights, Ollama 0.12.3, same prompt, JSON mode, temperature 0, num_ctx 4096. IDs recorded locally after pulling (evidence/step4/ollama-list.txt)." },
  ], { x: 0.5, y: 3.85, w: 9, h: 0.9, fontSize: 11.5 });
  sl.addNotes("Full weights digests: gemma 7cd4618c1faf8b7233c6c906dac1694b6a47684b37b8895d470ac688520b9c01; qwen 85e4a5b7b8ef0e48af0e8658f5aaab9c2324c76c1641493f4d1e25fce54b18b9; llama 667b0c1932bc6ffc593ed1d03f895bf2dc8dc6df21db3042284a6f4416b06a29. Local IDs match the ollama.com registry IDs.");
}

// ================= 6 Golden set =================
{
  const sl = contentSlide("Golden set: 160 tickets, κ = 0.896, frozen before testing", "Requirements");
  stat(sl, 0.5, 0.95, 1.6, "160", "tickets, rows 9840–9999");
  stat(sl, 2.2, 0.95, 1.6, "κ 0.896", "Cohen's kappa (146/160 agree)", C.accent1);
  stat(sl, 3.9, 0.95, 1.6, "14", "disagreements, all resolved and recorded", C.accent2);
  stat(sl, 5.6, 0.95, 1.8, "33 / 160", "consumer labels changed (20.6%): raw labels are noisy");
  txt(sl, "Labelling protocol (labelling_protocol.txt)", { x: 0.5, y: 2.05, w: 4.4, h: 0.3, fontSize: 13, bold: true, color: C.text2 });
  txt(sl, [
    { text: "Decide by the customer's problem and the resolution they want (added in revision 2, 7 Oct)", options: { bullet: { indent: 12 }, breakLine: true } },
    { text: "Several fits → the most-mentioned theme; ties → the order of the category list", options: { bullet: { indent: 12 }, breakLine: true } },
    { text: "Mortgage outranks loan or debt; Money transfer is the lowest priority", options: { bullet: { indent: 12 }, breakLine: true } },
    { text: "Credit card excludes credit-card debt; Debt collection includes collector activity after settlement", options: { bullet: { indent: 12 } } },
  ], { x: 0.5, y: 2.4, w: 4.4, h: 1.75, fontSize: 11, paraSpaceAfter: 4 });
  txt(sl, "Process: one member labelled, a second reviewed each label. The reviewer saw the first label (not blind), so κ is likely inflated.", { x: 0.5, y: 4.25, w: 4.4, h: 0.6, fontSize: 10, italic: true, color: C.accent5 });
  txt(sl, "Resolved disagreements", { x: 5.2, y: 2.05, w: 4.3, h: 0.3, fontSize: 13, bold: true, color: C.text2 });
  const ex = (y, head, body) => {
    card(sl, 5.2, y, 4.3, 0.95);
    txt(sl, [{ text: head, options: { bold: true, breakLine: true } }, { text: body }], { x: 5.32, y: y + 0.08, w: 4.06, h: 0.82, fontSize: 10.5 });
  };
  ex(2.4, "Row 9928: loan from Western Finance, then collection pressure", "Labeller: Consumer loan · Reviewer: Debt collection → Debt collection (collection activity dominates the complaint)");
  ex(3.5, "Row 9880: Cash App card activation, account and money taken", "Labeller: Bank account · Reviewer: Money transfer → Money transfer (payment-app service, not a bank)");
  sl.addNotes("Golden distribution: Credit reporting 33, Bank account 30, Money transfer 28, Debt collection 24, Mortgage 18, Consumer loan 16, Credit card 11. Disagreements: labeller won 8, reviewer won 6. kappa from scripts/agreement.py → evidence/step1/agreement.txt. Raw consumer label vs final golden: kappa 0.751. Golden set committed before any model saw it (commit 0013266; freeze 3567f80).");
}

// ================= 7 Environment =================
pres.addSection({ title: "Testing" });
{
  const sl = contentSlide("Test environment: service and load generator kept apart", "Testing");
  const machine = (x, title, lines, fill) => {
    card(sl, x, 0.95, 4.4, 2.3, fill);
    txt(sl, title, { x: x + 0.15, y: 1.05, w: 4.1, h: 0.3, fontSize: 13, bold: true, color: C.text2 });
    txt(sl, lines.map((l, i) => ({ text: l, options: { bullet: { indent: 12 }, breakLine: i < lines.length - 1 } })), { x: x + 0.15, y: 1.4, w: 4.1, h: 1.8, fontSize: 10.5, paraSpaceAfter: 2 });
  };
  machine(0.5, "Service PC: API + PostgreSQL + Ollama", [
    "Lenovo 83JT laptop, Intel Core Ultra 7 256V: 4 performance + 4 low-power cores, 8 threads",
    "16 GB RAM; Docker VM limited to 8 CPUs / 7.5 GiB",
    "Windows 11 Home 10.0.26200; Docker 29.5.3, Compose v5.1.4",
    "Ollama 0.12.3: library=cpu, '100% CPU', NUM_PARALLEL 1",
    "Wi-Fi 7 adapter; on mains power, sleep disabled",
  ], "DDF0EE");
  machine(5.1, "Load-generator PC: JMeter only", [
    "MSI MS-7C91 desktop, AMD Ryzen 5 3600, 6 cores / 12 threads",
    "32 GB RAM; Windows 10 Pro 22H2",
    "Apache JMeter 5.6.3 on Temurin OpenJDK 17.0.20.1, no plugins",
    "Wired Ethernet 1 Gbps to the same router",
    "✓ Never co-hosted with the service",
  ], "FBEBDD");
  txt(sl, "How results scale to the client", { x: 0.5, y: 3.4, w: 4.4, h: 0.3, fontSize: 13, bold: true, color: C.text2 });
  txt(sl, "Inference is single-stream and CPU-bound, so capacity ≈ 3,600 ÷ per-ticket latency. A server with faster cores cuts latency roughly in proportion; running more Ollama instances on more cores raises throughput roughly linearly until memory bandwidth limits it (an estimate, not measured).", { x: 0.5, y: 3.72, w: 4.4, h: 1.4, fontSize: 10.5 });
  txt(sl, "Limitations", { x: 5.1, y: 3.4, w: 4.4, h: 0.3, fontSize: 13, bold: true, color: C.text2 });
  txt(sl, [
    { text: "Laptop thermals and hybrid cores; WSL2 VM overhead", options: { bullet: { indent: 12 }, breakLine: true } },
    { text: "Home Wi-Fi, not isolated: JMeter time exceeds server time by a median of 34 ms (p95 112 ms)", options: { bullet: { indent: 12 }, breakLine: true } },
    { text: "About 35 POSTs per 20-min window, so p99 ≈ maximum", options: { bullet: { indent: 12 }, breakLine: true } },
    { text: "Extract clipped to 200–2,000 characters", options: { bullet: { indent: 12 } } },
  ], { x: 5.1, y: 3.72, w: 4.4, h: 1.4, fontSize: 10.5, paraSpaceAfter: 2 });
  sl.addNotes("Evidence: evidence/step4/service-hardware.txt, load-generator-hardware.txt, jmeter-version.txt, ollama-server-config.txt; evidence/step5/deploy-*.txt (ollama ps shows 100% CPU, context 4096). The Intel Arc iGPU is unused: Ollama runs in a Linux container without GPU passthrough. The 34 ms network overhead was measured over 2,956 successful load-test requests by matching JMeter samples to API log lines.");
}

// ================= 8 Playbook =================
{
  const sl = contentSlide("Playbook: freeze, deploy, measure, reconcile", "Testing");
  const steps = [
    ["1 Freeze", "Golden set + predictions committed (3567f80) before any model run"],
    ["2 Deploy", "switch_model.ps1: save logs, set tag, 2 synthetic warm-ups, TRUNCATE, check /stats = 0"],
    ["3 Accuracy", "160 golden tickets, one at a time, via POST /tickets; non-201 = wrong + non-conformant"],
    ["4 Load", "Redeploy (empty DB); 3 levels × 3 runs from the load-generator PC"],
    ["5 Stress", "Qwen3 4B: POST ramp 60 → 1,200/h over 40 min; search fixed at 316/h"],
    ["6 Reconcile", "save_logs.ps1 → analyse_jtl.py: every JMeter sample ↔ log line by request ID; /stats delta"],
  ];
  steps.forEach(([h, b], i) => {
    const x = 0.5 + (i % 3) * 3.05, y = 0.95 + Math.floor(i / 3) * 1.25;
    card(sl, x, y, 2.85, 1.1, i === 4 ? "FBEBDD" : "DDF0EE");
    txt(sl, [{ text: h, options: { bold: true, color: HEX.dk2, fontSize: 13, breakLine: true } }, { text: b }], { x: x + 0.12, y: y + 0.08, w: 2.62, h: 0.96, fontSize: 10.5 });
  });
  card(sl, 0.5, 3.55, 9.0, 1.6, "F4F6F7");
  txt(sl, "Open-loop JMeter configuration (step5/jmeter/ticket_triage.jmx)", { x: 0.65, y: 3.62, w: 8.7, h: 0.28, fontSize: 12, bold: true, color: C.text2 });
  txt(sl, [
    { text: "Two Open Model Thread Groups (POST, search). Schedule: rate(R/hour) random_arrivals(22 min) pause(1 min), so arrivals never wait for responses.", options: { bullet: { indent: 12 }, breakLine: true } },
    { text: "First 2 min = warm-up, excluded; 20-min measurement window; arrival seeds 1, 2, 3; 60 s cooldown between runs.", options: { bullet: { indent: 12 }, breakLine: true } },
    { text: "Data: 840 non-golden team rows (9000–9839) as JSON bodies; 20 search terms. Timeouts: connect 10 s, response 310 s.", options: { bullet: { indent: 12 }, breakLine: true } },
    { text: "Each request has X-Request-ID = UUID, saved in the .jtl and in the API log. Full procedure: step5/README.md.", options: { bullet: { indent: 12 } } },
  ], { x: 0.65, y: 3.92, w: 8.7, h: 1.2, fontSize: 10.5, paraSpaceAfter: 2 });
  sl.addNotes("Metric definitions (analyse_jtl.py): window = [t0 + warm-up, t0 + warm-up + 20 min) by request start time; p50/p95/p99 = nearest-rank over all samples in the window, failures included; achieved/h = successful requests completing inside the window; error % = JMeter success=false. Each run reuses the same ticket order, so content is controlled and only arrival timing varies between runs.");
}

// ================= 9 Load & stress =================
pres.addSection({ title: "Results" });
{
  const sl = contentSlide("Load and stress: Ollama inference is the bottleneck", "Results");
  const rows = [[hdr("Model"), hdr("POST/h"), hdr("p50 s"), hdr("p95 s [min–max]"), hdr("p99 s"), hdr("Done/h"), hdr("Err %")]];
  const lvlName = { average: "43", peak: "81", headroom: "105" };
  MODELS.forEach((m) => ["average", "peak", "headroom"].forEach((lv, j) => {
    const r = lvl(m.key, lv, "POST /tickets");
    const p95 = `${s(r.p95_ms_mean)} [${s(r.p95_ms_min)}–${s(r.p95_ms_max)}]`;
    const bad95 = +r.p95_ms_mean > 30000, badErr = +r.error_pct_mean > 1;
    rows.push([
      cell(j === 0 ? m.name : "", { bold: true, color: m.color }), cell(lvlName[lv], lv === "headroom" ? { bold: true } : {}), cell(s(r.p50_ms_mean)),
      cell(p95, bad95 ? { bold: true, color: FAIL } : {}), cell(s(r.p99_ms_mean)), cell(Math.round(+r.achieved_per_h_mean)),
      cell((+r.error_pct_mean).toFixed(1) + (m.key === "llama3.1-8b" && lv === "headroom" ? "*" : ""), badErr ? { bold: true, color: FAIL } : {}),
    ]);
  }));
  sl.addTable(rows, { x: 0.5, y: 0.95, w: 5.15, colW: [1.05, 0.6, 0.55, 1.25, 0.55, 0.6, 0.55], fontSize: 9.5, border: { type: "solid", color: "D5DEE1", pt: 0.5 }, margin: 0.03, rowH: 0.24, valign: "middle" });
  txt(sl, "Mean of 3 runs (open-loop, 20-min windows). GET /search p95 ≤ 0.38 s in all 27 runs; 0 search errors. *Llama: 2 JMeter test-end aborts; server returned 201 for both.", { x: 0.5, y: 3.45, w: 5.15, h: 0.5, fontSize: 9, italic: true, color: C.accent5 });
  const mins = timeline.map((t) => t.minute);
  sl.addChart(pres.charts.LINE, [
    { name: "Offered/min", labels: mins, values: timeline.map((t) => +t.post_arrivals) },
    { name: "Completed OK/min", labels: mins, values: timeline.map((t) => +t.post_completed_ok) },
    { name: "Backlog", labels: mins, values: timeline.map((t) => +t.approx_backlog) },
  ], {
    x: 5.85, y: 0.9, w: 3.65, h: 2.75, chartColors: [HEX.accent3, HEX.accent1, HEX.accent4], lineSize: 1.5, lineDataSymbol: "none",
    showTitle: true, title: "Qwen3 4B stress ramp: POST per minute", titleFontSize: 10, titleColor: HEX.dk2, titleFontFace: "+mn-lt",
    showLegend: true, legendPos: "b", legendFontSize: 8, legendFontFace: "+mn-lt", catAxisLabelFontSize: 8, valAxisLabelFontSize: 8, catAxisLabelFontFace: "+mn-lt", valAxisLabelFontFace: "+mn-lt",
    catAxisLabelColor: "5A6A70", valAxisLabelColor: "5A6A70", valGridLine: { color: "E1E7EA", size: 0.5 }, catGridLine: { style: "none" }, catAxisLabelFrequency: 5,
    catAxisTitle: "minute", showCatAxisTitle: true, catAxisTitleFontSize: 8, catAxisTitleColor: "5A6A70",
  });
  txt(sl, [
    { text: "Limit found: ~470–480 tickets/h. ", options: { bold: true } },
    { text: "Up to 450/h offered it keeps up (backlog ≤ 3). From minute 21 (~600/h offered) the backlog rises every minute, latency grows 52 s → 280 s, and from minute 30 requests fail with 502 at the 300 s timeout. Search p95 stays 0.13 s." },
  ], { x: 5.85, y: 3.7, w: 3.65, h: 1.5, fontSize: 10 });
  txt(sl, [
    { text: "Diagnosis: ", options: { bold: true } },
    { text: "NUM_PARALLEL = 1, so tickets queue behind the model; nothing else saturates. Gemma has spare capacity but rejects 16.5% of tickets. Llama (13 s per ticket) has no burst margin: random clusters gave p95 from 18 s to 90 s across runs at 105/h." },
  ], { x: 0.5, y: 3.98, w: 5.15, h: 1.2, fontSize: 10 });
  sl.addNotes("Source: step5/results/levels.csv, runs.csv, summary.md and the stress timeline.csv. Llama headroom per run: p95 18.2 s / 34.7 s / 89.7 s; run 3 had 5 arrivals within ~1.2 min. Reconciliation: 3,640 JMeter samples across 28 runs, every one matched to a service-log line; 73 status mismatches, all JMeter test-end aborts (71 in the stress run, 2 in Llama headroom run 3), where the server log shows the real outcome.");
}

// ================= 10 Accuracy =================
{
  const sl = contentSlide("Accuracy: no candidate reaches 85%; Llama best at 75.6%", "Results");
  const labels = [...CATS.map((c) => c.replace(" or service", "")), "Overall"];
  sl.addChart(pres.charts.BAR, MODELS.map((m) => ({
    name: m.name, labels,
    values: [...CATS.map((c) => acc[m.key].per_category[c].accuracy_pct), acc[m.key].overall_accuracy_pct],
  })), {
    x: 0.4, y: 0.9, w: 5.9, h: 4.2, barDir: "col", barGrouping: "clustered", chartColors: MODELS.map((m) => m.color), barGapWidthPct: 40,
    showTitle: true, title: "Accuracy on the golden set (%). R6 needs ≥ 70 per category, R5 ≥ 85 overall", titleFontSize: 10, titleColor: HEX.dk2, titleFontFace: "+mn-lt",
    valAxisMaxVal: 100, valAxisMinVal: 0, valAxisMajorUnit: 25, showLegend: true, legendPos: "t", legendFontSize: 9, legendFontFace: "+mn-lt",
    catAxisLabelFontSize: 8, valAxisLabelFontSize: 8, catAxisLabelFontFace: "+mn-lt", valAxisLabelFontFace: "+mn-lt", catAxisLabelColor: "5A6A70", valAxisLabelColor: "5A6A70",
    valGridLine: { color: "E1E7EA", size: 0.5 }, catGridLine: { style: "none" },
  });
  MODELS.forEach((m, i) => {
    const a = acc[m.key];
    const y = 0.95 + i * 0.75;
    txt(sl, `${(+a.overall_accuracy_pct).toFixed(1)}%`, { x: 6.55, y, w: 1.25, h: 0.45, fontSize: 22, bold: true, color: m.color, fontFace: THEME.headFontFace });
    txt(sl, [{ text: m.name, options: { bold: true, breakLine: true } }, { text: `${a.correct}/160 · valid output ${a.output_conformance_pct}%` }], { x: 7.8, y: y + 0.02, w: 1.75, h: 0.6, fontSize: 9.5 });
  });
  txt(sl, "Where each model goes wrong", { x: 6.55, y: 3.25, w: 3, h: 0.28, fontSize: 12, bold: true, color: C.text2 });
  txt(sl, [
    { text: "Gemma: 26 of 29 invalid answers are capitalisation ('Consumer Loan'); 18/30 Bank → Credit reporting; Money transfer 0/28", options: { bullet: { indent: 12 }, breakLine: true } },
    { text: "Qwen: 9/33 Credit reporting → Credit card; 3 lowercase answers (R7 98.1%)", options: { bullet: { indent: 12 }, breakLine: true } },
    { text: "Llama: errors spread out; 16 tickets wrongly sent to Credit card; Bank account 66.7%", options: { bullet: { indent: 12 } } },
  ], { x: 6.55, y: 3.55, w: 3.0, h: 1.65, fontSize: 9.5, paraSpaceAfter: 3 });
  sl.addNotes("Confusion matrices: step5/results/<model>/accuracy/summary.md and confusion_matrix.csv. Sequential single-request latency (p50): Gemma 2.4 s, Qwen 7.9 s, Llama 13.2 s. Categories ≥ 70%: Gemma 0/7, Qwen 4/7 (fails Credit reporting 51.5%, Debt collection 62.5%, Bank 66.7%), Llama 4/7 (fails Credit reporting 69.7%, Bank 66.7%, Consumer loan 68.8%).");
}

// ================= 11 Predictions + recommendation =================
pres.addSection({ title: "Recommendation" });
{
  const sl = contentSlide("Recommendation: Qwen3 4B, for assisted routing only", "Recommendation");
  const V = {
    "gemma3-1b": ["FAIL", "PASS", "PASS", "FAIL", "FAIL", "FAIL", "FAIL", "PASS"],
    "qwen3-4b": ["PASS†", "PASS", "PASS", "PASS", "FAIL", "FAIL", "FAIL", "PASS"],
    "llama3.1-8b": ["FAIL", "FAIL", "PASS", "PASS*", "FAIL", "FAIL", "PASS", "PASS"],
  };
  const vrows = [[hdr("Req"), hdr("Gemma"), hdr("Qwen"), hdr("Llama")]];
  ["R1 Throughput", "R2 POST latency", "R3 Search", "R4 Errors", "R5 Accuracy", "R6 Per category", "R7 Conformance", "R8 CPU-only"].forEach((r, i) =>
    vrows.push([cell(r, { bold: true }), verdict(V["gemma3-1b"][i]), verdict(V["qwen3-4b"][i]), verdict(V["llama3.1-8b"][i])]));
  sl.addTable(vrows, { x: 0.5, y: 0.95, w: 3.4, colW: [1.3, 0.7, 0.7, 0.7], fontSize: 9, border: { type: "solid", color: "FFFFFF", pt: 1 }, margin: 0.03, rowH: 0.24, valign: "middle" });
  txt(sl, "† 102 of 103/h offered completed, backlog ≤ 1; stress run sustained 430/h. * server 0 errors; JMeter 1.9% from test-end aborts.", { x: 0.5, y: 3.2, w: 3.4, h: 0.45, fontSize: 8.5, italic: true, color: C.accent5 });
  const prow = (a, b, c, ok) => [cell(a, { bold: true }), cell(b), cell(c), cell(ok ? "✓" : "✗", { bold: true, color: ok ? PASS : FAIL, align: "center" })];
  const prows = [[hdr("Prediction"), hdr("Predicted"), hdr("Measured"), hdr("")],
    prow("Bottleneck", "Ollama CPU; 502 at 300 s", "Confirmed", true),
    prow("Accuracy G/Q/L", "52 / 74 / 71%", "30 / 69 / 76%", false),
    prow("Latency G/Q/L", "1.5 / 5 / 10 s", "2.4 / 7.9 / 13.2 s", false),
    prow("Qwen limit", "~700/h", "~470/h", false),
    prow("Hardest category", "Money transfer", "Gemma only", false),
    prow("Llama R1, R2", "pass", "fail", false)];
  sl.addTable(prows, { x: 0.5, y: 3.65, w: 3.4, colW: [1.05, 1.0, 1.05, 0.3], fontSize: 8.5, border: { type: "solid", color: "D5DEE1", pt: 0.5 }, margin: 0.03, rowH: 0.2, valign: "middle" });
  card(sl, 4.15, 0.95, 5.35, 2.3, "DDF0EE");
  txt(sl, [
    { text: "Deploy Qwen3 4B (0edcdef34593) to suggest a category that an agent confirms", options: { bold: true, color: HEX.dk2, fontSize: 12, breakLine: true } },
    { text: "The only candidate meeting every service requirement (R1–R4, R8) at peak + 30%: p95 11.8 s against 30 s, 0% errors, and capacity ~470/h (4.5× the 105/h need), which absorbs bursts and surges.", options: { bullet: { indent: 12 }, breakLine: true } },
    { text: "Llama is 6.8 points more accurate and the only model passing R7, but on this CPU it fails R1 and R2 (p95 up to 90 s). We do not trade peak capacity for accuracy that still misses R5.", options: { bullet: { indent: 12 }, breakLine: true } },
    { text: "Gemma is ruled out: 16.5% of tickets rejected, 30% accurate.", options: { bullet: { indent: 12 } } },
  ], { x: 4.3, y: 1.03, w: 5.05, h: 2.22, fontSize: 10, paraSpaceAfter: 3 });
  card(sl, 4.15, 3.4, 5.35, 0.8, "FBE3E0");
  txt(sl, [
    { text: "Not met by any candidate: ", options: { bold: true, color: FAIL } },
    { text: "R5 (85% overall) and R6 (70% per category). Qwen also misses R7 (98.1%). Fully automatic routing cannot be promised on this hardware." },
  ], { x: 4.3, y: 3.47, w: 5.05, h: 0.7, fontSize: 10 });
  txt(sl, [
    { text: "Why our predictions were wrong: ", options: { bold: true } },
    { text: "we modelled 8 equal cores, but the 256V has 4 low-power cores and runs inference inside WSL2, the likely reason every model ran 1.3–1.6× slower (not measured separately). We reasoned from mean utilisation and ignored Poisson bursts (Llama R2). The prompt lacks our protocol's rules, which caps accuracy. " },
    { text: "Assignment 2: ", options: { bold: true } },
    { text: "case-insensitive parsing, protocol rules in the prompt, more cores per Ollama instance." },
  ], { x: 4.15, y: 4.27, w: 5.35, h: 0.95, fontSize: 9.5 });
  sl.addNotes("Full verdict reasoning in step5/RESULTS.md sections 5–7. Predictions frozen in STEP4.md at commit 3567f80. Hardest-category outcome: Gemma Money transfer 0% (as predicted); Qwen's hardest was Credit reporting 51.5% (9 to Credit card, and only 4 of those 9 mention a card, so the cause is not yet diagnosed); Llama's hardest was Bank account 66.7%. Assisted routing: at 68.8% accuracy, about 2 in 3 tickets need only a confirmation; a misroute costs one agent correction.");
}

// ================= 12 References =================
{
  const sl = contentSlide("References and acknowledgements", "Recommendation");
  const refs = [
    "Consumer Financial Protection Bureau. Consumer Complaint Database. consumerfinance.gov/data-research/consumer-complaints (course extract, team rows 9000–9999)",
    "[R1] Barclays (2026). UK complaints data, January to June 2026. home.barclays/who-we-are/reporting/uk-complaints-data",
    "[R2] CFPB (2024, 2025). Consumer Response Annual Reports 2023, 2024. files.consumerfinance.gov",
    "[R3] CFPB Consumer Complaint Database API, daily counts (retrieved 1 Oct 2026)",
    "[R4] Financial Conduct Authority (2026). Aggregate complaints data 2025 H2. fca.org.uk/data/complaints-data",
    "[R5] FIDReC (2025). FIDReC received a record 4,355 claims this fiscal year. fidrec.com.sg",
    "[R6] Call Centre Helper. 10 Things You Need to Know About Call Centres. callcentrehelper.com",
    "[R7] Taylor, J. W. (2012). Density forecasting of intraday call center arrivals. Management Science 58, 534–549",
  ];
  const sw = [
    "Ollama 0.12.3, MIT License. github.com/ollama/ollama",
    "Gemma 3 (Google DeepMind), Gemma Terms of Use. ai.google.dev/gemma/terms",
    "Qwen3-4B-Instruct-2507 (Alibaba Qwen), Apache License 2.0. huggingface.co/Qwen/Qwen3-4B-Instruct-2507",
    "Llama 3.1 8B Instruct (Meta), Llama 3.1 Community License. Built with Llama. huggingface.co/meta-llama/Llama-3.1-8B-Instruct",
    "Apache JMeter 5.6.3, Apache License 2.0 · PostgreSQL 16, PostgreSQL License · FastAPI, MIT",
    "AI assistance: Claude Code (Anthropic) helped build the service and test tooling, as permitted by the brief. Labelling, test runs and judgements are the team's.",
  ];
  txt(sl, "Data and workload sources", { x: 0.5, y: 0.95, w: 4.4, h: 0.3, fontSize: 12, bold: true, color: C.text2 });
  txt(sl, refs.map((r, i) => ({ text: r, options: { breakLine: i < refs.length - 1 } })), { x: 0.5, y: 1.3, w: 4.4, h: 3.9, fontSize: 9.5, paraSpaceAfter: 5 });
  txt(sl, "Software, model licences, acknowledgements", { x: 5.1, y: 0.95, w: 4.4, h: 0.3, fontSize: 12, bold: true, color: C.text2 });
  txt(sl, sw.map((r, i) => ({ text: r, options: { breakLine: i < sw.length - 1 } })), { x: 5.1, y: 1.3, w: 4.4, h: 3.9, fontSize: 9.5, paraSpaceAfter: 5 });
  sl.addNotes("Full URLs: workload/WORKLOAD.md references section and STEP4.md section 2 (licence links). The Llama 3.1 Community License requires displaying 'Built with Llama'.");
}

(async () => {
  await pres.writeFile({ fileName: OUT });
  if (APPLY_THEME) {
    const { applyTheme } = require(APPLY_THEME);
    await applyTheme(OUT, THEME);
  }
  console.log("wrote", OUT);
})();
